version: '3.1'
services:
  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - "80:80"
    volumes:
      - ./www/:/wp_www/:rw
      - ./ssl:/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php1
    restart: always
    environment:
      TZ: Asia/Taipei
  php1:
    build: ./
    volumes:
      - ./www/:/wp_www/:rw
    links:
      - mysql
    restart: always
    environment:
      TZ: Asia/Taipei
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      WORDPRESS_TABLE_PREFIX: wpa_
    cap_add:
      - SYS_PTRACE
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Asia/Taipei
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
